name: Continuous Deployment Workflow

on:
  push:
    branches:
      - "main"

  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: ./web

jobs:
  # ======================================================
  # Deploying the main branch to staging
  #
  # It's important to test the main branch in staging
  # before going to production with it.
  # ======================================================
  deploy_staging:
    name: "Deploy to staging"
    environment: staging
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3

      # ======================================================
      # Set up Bun
      # ======================================================
      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: "latest"

      - name: "Deploy to staging"
        uses: burnett01/rsync-deployments@23a557dceb19f9bb960ef40cf75cab5e9b37ec1f
        with:
          switches: -avzr --delete
          path: ./web
          remote_path: /var/app
          remote_host: ${{ secrets.HOSTNAME }}
          remote_user: ${{ secrets.REMOTE_USER }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: "Execute SSH commands on remote server"
        uses: JimCronqvist/action-ssh@7737f1192ddd8376686e9d6354dea44592c942bf
        with:
          hosts: "${{ secrets.REMOTE_USER }}@${{ secrets.HOSTNAME }}"
          privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
          command: |
            cd /var/app/web
            bun install
            bun run build

  # ======================================================
  # Deploy the main branch to production
  #
  # This job will require the `deploy_staging` job to
  # run and complete successfully first!
  #
  # WARNING: this job will syc all the files that are
  # in the folder ./web/ to the production server
  # while removing all the files that are already
  # in the production server!
  # ======================================================
  deploy_production:
    name: "Deploy to production"
    environment: production
    runs-on: ubuntu-latest
    needs: deploy_staging

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3

      # ======================================================
      # Set up Bun
      # ======================================================
      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: "latest"

      - name: "Deploy to production"
        uses: burnett01/rsync-deployments@23a557dceb19f9bb960ef40cf75cab5e9b37ec1f
        with:
          switches: --avzr --delete
          path: ./web
          remote_path: /var/app
          remote_host: ${{ secrets.HOSTNAME }}
          remote_user: ${{ secrets.REMOTE_USER }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: "Execute SSH commands on remote server"
        uses: JimCronqvist/action-ssh@7737f1192ddd8376686e9d6354dea44592c942bf
        with:
          hosts: "${{ secrets.REMOTE_USER }}@${{ secrets.HOSTNAME }}"
          privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
          command: |
            cd /var/app/web
            bun install
            bun run build
