name: Continuous Integration

on:
  push:
    paths:
      - "web/packages/**"
  pull_request:
    paths:
      - "web/packages/**"
    branches:
      - main
      - development
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: ./web

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: "latest"

      - name: Cache Bun modules
        id: cache-bun-modules
        uses: actions/cache@v3
        with:
          path: ~/.bun
          key: ${{ runner.os }}-bun-${{ hashFiles('web/packages/**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v3
        with:
          path: |
            web/packages/**/node_modules
            !node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('web/packages/**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: Install dependencies
        run: bun install
        if: steps.cache-node-modules.outputs.cache-hit != 'true' || steps.cache-bun-modules.outputs.cache-hit != 'true'

      - name: Run build
        run: bun run build

      - name: Run tests
        run: bun run test

  lint:
    name: Linting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: "latest"

      - name: Cache Bun modules
        id: cache-bun-modules
        uses: actions/cache@v3
        with:
          path: ~/.bun
          key: ${{ runner.os }}-bun-${{ hashFiles('web/packages/**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v3
        with:
          path: |
            web/packages/**/node_modules
            !node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('web/packages/**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-

      - name: Install dependencies
        run: bun install
        if: steps.cache-node-modules.outputs.cache-hit != 'true' || steps.cache-bun-modules.outputs.cache-hit != 'true'

      - name: Run build
        run: bun run build

      - name: Run lint
        run: bun run lint
